name: Sync Repositories

on:
  push:
    branches:
      - main  # Déclencher la synchronisation lors d'un push sur la branche main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt courant
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TARGET_REPO_TOKEN }}  # Utilisez le token GitHub par défaut

    # Étape 2 : Configurer Git
    - name: Configure Git
      run: |
        git config --global user.name "igorgaetan"
        git config --global user.email "igorkwenja@github.com"
    # Étape 3 : Ajouter le dépôt cible comme remote
    - name: Add target repository as remote
      run: |
        git remote add target https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/igorgaetan/sade-automation-script-deployment.git
        git fetch target
        
    # Étape 4 : Pousser les modifications vers le dépôt cible
    - name: Push changes to target repository
      run: |
        git push target main:main  # Pousser la branche main du dépôt courant vers la branche main du dépôt cible
